sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: 6
script:
  - npm run build
after_success:
  - surge --project ./dist --domain web-audio-api-synth.surge.sh
#  - npm run report-coverage
#  - npm run release